---
title: Apresentação do Curso<br><br>
title-slide-attributes:
    data-background-size: contain
    data-background-position-x: center
    data-background-position-y: center
---

## Conteúdo Programático
::: {.nonincremental}
::: {.fontsize90}
- Conceitos Básicos de Orientação a Objetos
    - Classes, Objetos, Atributos e Métodos
    - Estado de Objeto
    - Visibilidade e Encapsulamento
    - Construtores, Destrutores e Identidade de Objetos
    - Atributos e Métodos Estáticos
    - Sobrecarga de Métodos
- Composição, Agregação e Associação
- Pacotes e Coleções
- Coesão, Acoplamento e Projeto Baseado em Responsabilidade
- Herança
- Sobrescrição de Métodos
:::
:::


## Objetivos
Ao final do curso é esperado que o aluno:

- Tenha uma visão geral do paradigma de programação orientada a objetos.
- Seja capaz de implementar algoritmos para a solução de problemas computacionais em uma linguagem de programação orientada a objetos. 


## GAC125 em 2024/1

17 semanas de curso:

- Aulas teóricas não presenciais (16 semanas): 11/03/2024 a 30/06/2024.
- Aulas práticas presenciais (16 semanas): 11/03/2024 a 30/06/2024.
- Avaliação adicional: 01/07/2024 a 03/07/2024.


## Avaliações
- **Exercícios Avaliativos:** 20 pontos (2 pontos cada exercício avaliativo).
    - Teremos exercício avaliativo em **quase todos os dias de aula prática**.
    - Serão **exercícios curtos** feitos no **início das aulas práticas**.
    - O **conteúdo** avaliado será **todo** aquele **apresentado após o último exercício avaliativo**.
- **Prova 1:** 22/04 a 24/04: 25 pontos.
- **Prova 2:** 20/05 a 22/05: 25 pontos.
- **Prova 3:** 24/06 a 26/06: 30 pontos.



## Observações Importantes
- A aferição de frequência será realizada por **chamada oral** uma vez em cada dia de **aula prática presencial** em qualquer momento entre o início e o término da mesma. 
    - Para ter **presença na aula prática**, além de comparecer à aula, o **aluno deve realizar e entregar o(s) exercício(s) proposto(s) na aula**.  
- Nas **aulas não presenciais (ANP), a presença** estará condicionada ao **preenchimento de um questionário ou entrega de exercício** disponibilizado no Campus Virtual.
- As provas poderão ter exercícios teóricos e/ou de implementação (linguagem Java).
- As provas deverão ser realizadas individualmente. 
- O conteúdo avaliado em cada prova é todo aquele dado até a semana anterior à da realização da prova. Observe que isso significa que o conteúdo das provas á acumulativo.
    • Revisões de provas serão feitas no máximo até 15 dias letivos após a divulgação das notas.
    • Qualquer entrega de material (exercícios, questionários, provas etc.) deve ser feita única e exclusivamente por meio do Campus Virtual.
    • Exercícios, questionários e provas entregues via Campus Virtual também serão avaliados quanto a cópias e fraudes. Os alunos podem até discutir a resolução dos exercícios/questionários com os colegas, mas cada aluno deverá entregar a sua própria versão da resolução dos mesmos. As cópias/fraudes resultarão em nota zero e abertura de processo disciplinar.  
    • Segunda chamada de atividades avaliativas: apenas para alunos com pedidos de substituição de atividades acadêmicas aprovados pela PRG.